spring.datasource.url=jdbc:postgresql://localhost:5432/lvbank
spring.datasource.username=postgres
spring.datasource.password=1234567

spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:dev-only-troque-esse-segredo-por-um-bem-longo-123456}
jwt.expiration-ms=3600000